spring.application.name=backend

# DATABASE
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/reservations_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Paris}
spring.datasource.username=${DB_USERNAME:reservations}
spring.datasource.password=${DB_PASSWORD:reservations}

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SERVER
server.port=8085

# JWT
jwt.secret=${JWT_SECRET:bG9jYWwtZGV2ZWxvcG1lbnQtc2VjcmV0LWtleS0zMi1ieXRlcy0xMjM0NTY=}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

external.shows.api-url=${EXTERNAL_SHOWS_API_URL:https://opendata.brussels.be/api/explore/v2.1/catalog/datasets/lieux_culturels_touristiques_evenementiels_visitbrussels_vbx/records?limit=20}
